### ISSUE TITLE
Go Module support

### ISSUE THREAD

**Issue by johnfg10** [zencoder/go-dash#55]
Hello,

Great project you got here, I would like to suggest support for go's latest VGO modules feature, this makes managing librarys like this alot easier currently you can work around the lack of VGO support by using
`go get github.com/zencoder/go-dash@latest`
But it would be nice to have native support

**Comment by thomshutt** [comment]
Thanks for raising this @johnfg10 - we've been talking for a while about removing the need for any dependencies from this project (and thus obviating the need for any dependency management).

I've gone ahead and done that in https://github.com/zencoder/go-dash/pull/56 so if that's accepted and merged then it should be compatible with whatever system importers of the project are using.

**Comment by ozburo** [comment]
Just came across this project and issue since I was about to open this issue as well.

I'm trying to use this package w/ Go Modules (v1.12) and I'm getting the error:

"cannot load github.com/zencoder/go-dash: cannot find module providing package github.com/zencoder/go-dash"

Not sure how to solve this...
